#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd LeftDomain

rm system/cellSetDict > /dev/null 2>&1
rm -rf 0 surfaceElevation > /dev/null 2>&1
rm -rf constant/polyMesh > /dev/null 2>&1


cleanCase

cd ..

cd RightDomain

rm system/cellSetDict > /dev/null 2>&1
rm -rf 0 surfaceElevation > /dev/null 2>&1
rm -rf constant/polyMesh > /dev/null 2>&1


cleanCase

cd ..
# ----------------------------------------------------------------- end-of-file
