#!/bin/sh

# Run from this directory
cd ${0%/*} || exit 1

PWD=`pwd`
echo $PWD
domain1=$PWD/LeftDomain
domain2=$PWD/RightDomain

echo ${domain1}
echo ${domain2}

# Ranks set to each domain
numProcsDomain1=2
numProcsDomain2=2

cd ${domain2}
echo $(pwd)
solverDomain2=pisoFSIFoam
echo application is ${solverDomain2}
cd ..

cd ${domain1}
solverDomain1=pisoCPLFoam
echo application is ${solverDomain1}
cd ../

echo -n "running with MUI..."

# parMupSiF case with OpenFOAM_MUI(C++)_MUI(python)_FEniCS parallel run
mpirun -np ${numProcsDomain1} ${solverDomain1} -case ${domain1} -world ${domain1} -parallel  \
	< /dev/null > logFiles/log.domain1 2>&1 : \
       -np ${numProcsDomain2} ${solverDomain2} -case ${domain2} -world ${domain2} -parallel  \
        < /dev/null > logFiles/log.domain2 2>&1 

echo "Done"

# ----------------------------------------------------------------- end-of-file
